stages:
  - install
  - lint

variables:
  PYTHON_VERSION: "3.8" 

# Stage 1: Install dependencies
install_dependencies:
  stage: install
  image: python:${PYTHON_VERSION}
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  artifacts:
    paths:
      - .venv 

# Stage 2: Lint code
lint_code:
  stage: lint
  image: python:${PYTHON_VERSION}
  script:
    - pip install flake8
    - flake8 src dags
  rules:
    - changes:
        - "**/*.py"