name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Python 3.8
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    # Step 3: Install dependencies excluding `apache-airflow-providers-apache-spark`
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install pylint
        pip install scikit-learn
        pip install requests
        pip install mlflow
        pip install apache-airflow 
        pip install apache-airflow-providers-apache-spark
        pip install pyspark

    # Step 4: Analyze the code in the `src/` directory with Pylint
    - name: Analyze code with Pylint
      run: |
        pylint src/
